SET max_error_count=30000;

SELECT CONCAT(CURDATE()+0, CURTIME()+0);

LOAD DATA LOCAL INFILE '/vagrant/data.csv'
INTO TABLE db1.raw1
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(Symbol,Dateno,Open,High,Low,Close,Volume,OI);


SHOW WARNINGS;

SELECT CONCAT(CURDATE()+0, CURTIME()+0);
